name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Install
      run: sudo python3 setup.py develop 
      
    # - name: Run pep8 Checks
    #   run: make pep8
      
    # - name: Run Flake8 Checks
    #   run: make flake8
      
    # - name: Run Tests
    #   run: make test
  